export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  CREATE_TRANSACTIONS: 'CREATE_TRANSACTIONS',
  APPLY_DISCOUNTS: 'APPLY_DISCOUNTS',
  VOID_TRANSACTIONS: 'VOID_TRANSACTIONS',
  CANCEL_TRANSACTIONS: 'CANCEL_TRANSACTIONS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
